name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node and Rust
        uses: tauri-apps/setup-tauri@v1
        with:
          node-version: 18
          rust-version: stable

      - name: Install dependencies
        working-directory: web
        run: npm ci

      - name: Build Tauri app
        working-directory: web
        run: |
          npm run build
          npx tauri build

      - name: Upload installers
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-bundle
          path: web/src-tauri/target/release/bundle/**
